name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container: node:latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install modules
        run: npm i
      - name: Build app
        run: npm run build
      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: test
          MY_SECRET_KEY_JWT: qualquer-chave
